using UnityEngine;
using System.Collections;

public class PlayerController : MonoBehaviour
{
    public float moveSpeed = 5.0f;
    public float rotationSpeed = 90.0f;

    public Camera playerCamera; // ФЋИоЖѓ КЏМі УпАЁ

    private bool isRotating = false; // ШИРќ СпРЮСі ПЉКЮИІ ГЊХИГЛДТ КЏМі
    private bool isMoving = false; // РЬЕП СпРЮСі ПЉКЮИІ ГЊХИГЛДТ КЏМі

    void Update()
    {
        // P ХАИІ ДЉИІ ЖЇИЖДй ФЋИоЖѓ ШИРќ УГИЎ Йз РЬЕП
        if (Input.GetKeyDown(KeyCode.P) && !isRotating && !isMoving)
        {
            StartCoroutine(RotateAndMoveCamera(playerCamera.transform.right * 40f, -90));
        }

        // O ХАИІ ДЉИІ ЖЇИЖДй ФЋИоЖѓ ШИРќ УГИЎ Йз РЬЕП
        if (Input.GetKeyDown(KeyCode.O) && !isRotating && !isMoving)
        {
            StartCoroutine(RotateAndMoveCamera(-playerCamera.transform.right * 40f, 90));
        }
    }

    IEnumerator RotateAndMoveCamera(Vector3 moveDirection, float rotationAngle)
    {
        isRotating = true;
        float startRotation = playerCamera.transform.rotation.eulerAngles.y; // НУРл АЂЕЕ
        float targetRotation = startRotation + rotationAngle; // ИёЧЅ АЂЕЕ

        float elapsedTime = 0f; // АцАњ НУАЃ

        while (elapsedTime < 1f)
        {
            float currentAngle = Mathf.Lerp(startRotation, targetRotation, Mathf.SmoothStep(0f, 1f, elapsedTime)); // КЮЕхЗДАд АЂЕЕ КЏАц
            playerCamera.transform.rotation = Quaternion.Euler(45f, currentAngle, 0f);

            // РЬЕП
            if (!isMoving)
            {
                isMoving = true;
                StartCoroutine(MoveCamera(moveDirection));
            }

            elapsedTime += Time.deltaTime / 1f; // 1УЪ ЕПОШ ШИРќ
            yield return null;
        }
        isRotating = false;
    }

    IEnumerator MoveCamera(Vector3 moveDirection)
    {
        float elapsedTime = 0f; // АцАњ НУАЃ
        Vector3 startPosition = playerCamera.transform.position; // НУРл РЇФЁ
        Vector3 targetPosition = startPosition + moveDirection;

        while (elapsedTime < 1f)
        {
            playerCamera.transform.position = Vector3.Lerp(startPosition, targetPosition, Mathf.SmoothStep(0f, 1f, elapsedTime)); // КЮЕхЗДАд РЬЕП
            elapsedTime += Time.deltaTime / 1f; // 1УЪ ЕПОШ РЬЕП

            // ШИРќ
            float rotationAngle = Input.GetKeyDown(KeyCode.P) ? -90 : 90;
            float startRotation = playerCamera.transform.rotation.eulerAngles.y; // НУРл АЂЕЕ
            float targetRotation = startRotation + rotationAngle; // ИёЧЅ АЂЕЕ
            float currentAngle = Mathf.Lerp(startRotation, targetRotation, Mathf.SmoothStep(0f, 1f, elapsedTime)); // КЮЕхЗДАд АЂЕЕ КЏАц
            playerCamera.transform.rotation = Quaternion.Euler(45f, currentAngle, 0f);

            yield return null;
        }

        playerCamera.transform.position = targetPosition; // ИёЧЅ РЇФЁЗЮ КИСЄ
        isMoving = false;
    }
}
